// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import FrontendRedirectController from "./frontend_redirect_controller.js"
application.register("frontend-redirect", FrontendRedirectController)

import HeaderMenuController from "./header_menu_controller.js"
application.register("header-menu", HeaderMenuController)

import LocalTimeController from "./local_time_controller.js"
application.register("local-time", LocalTimeController)

import MessageFormController from "./message_form_controller.js"
application.register("message-form", MessageFormController)

import TrackMessageReadController from "./track_message_read_controller.js"
application.register("track-message-read", TrackMessageReadController)
