require:
  - standard
  - rubocop-rails
  - rubocop-minitest

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1.2

Rails:
  Enabled: true

Style/Documentation:
 Enabled: false


